# Generated by Django 3.1 on 2020-09-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='description',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Form Description'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='to_url',
            field=models.CharField(max_length=150, verbose_name='URL to ?'),
        ),
    ]
