# Generated by Django 3.1 on 2020-09-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='main_file',
            field=models.CharField(default='main.py', max_length=20, verbose_name='Main File Name Of Plugin'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Statue Of Plugin'),
        ),
    ]
