# Generated by Django 3.1 on 2020-10-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugin', '0003_auto_20200926_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginoption',
            name='plugin',
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
    ]
