# Generated by Django 3.1 on 2020-09-16 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Field Name')),
                ('description', models.CharField(max_length=50, verbose_name='Field Description')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required?')),
                ('field_type', models.CharField(max_length=50, verbose_name='Field Type')),
                ('placeholder', models.CharField(max_length=50, verbose_name='Field Placeholder')),
                ('custom_css', models.TextField(verbose_name='Field Custom CSS')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Form Name')),
                ('is_name', models.BooleanField(default=False, verbose_name='Name Field')),
                ('is_surname', models.BooleanField(default=False, verbose_name='Surname Field')),
                ('is_username', models.BooleanField(default=False, verbose_name='Username Field')),
                ('is_email', models.BooleanField(default=False, verbose_name='Email Field')),
                ('is_password', models.BooleanField(default=False, verbose_name='Password Field')),
                ('is_text', models.BooleanField(default=False, verbose_name='Text Field (short)')),
                ('is_article', models.BooleanField(default=False, verbose_name='Text Field (long)')),
                ('is_image', models.BooleanField(default=False, verbose_name='Image Field')),
                ('is_file', models.BooleanField(default=False, verbose_name='File Field')),
                ('is_options', models.BooleanField(default=False, verbose_name='Options Field')),
                ('is_boolean', models.BooleanField(default=False, verbose_name='Boolean Field')),
                ('to_url', models.URLField(max_length=150, verbose_name='URL to ?')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dark', models.BooleanField(default=False, verbose_name='Karanlık Mod')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Settings')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bio')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil Fotoğrafı')),
                ('website_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Website URL')),
                ('lang', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bio')),
                ('facebook_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Website URL')),
                ('instagram_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Website URL')),
                ('twitter_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Website URL')),
                ('github_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Website URL')),
                ('linkedin_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Website URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
        ),
    ]
