# Generated by Django 3.1 on 2020-09-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='is_article',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_boolean',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_email',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_file',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_name',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_options',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_password',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_surname',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_text',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='is_username',
        ),
        migrations.AddField(
            model_name='forms',
            name='description',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Form Name'),
        ),
        migrations.AddField(
            model_name='forms',
            name='slug',
            field=models.SlugField(default='', verbose_name='Form Slug'),
        ),
        migrations.AlterField(
            model_name='formfields',
            name='custom_css',
            field=models.TextField(blank=True, null=True, verbose_name='Field Custom CSS'),
        ),
        migrations.AlterField(
            model_name='formfields',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Github URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Linkedin URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Twitter URL'),
        ),
        migrations.CreateModel(
            name='FormFieldsStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.formfields', verbose_name='Field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.forms', verbose_name='Form')),
            ],
        ),
    ]
