# Generated by Django 3.1 on 2020-09-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200917_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfieldsstorage',
            name='field',
        ),
        migrations.RemoveField(
            model_name='formfieldsstorage',
            name='form',
        ),
        migrations.DeleteModel(
            name='FormFields',
        ),
        migrations.DeleteModel(
            name='FormFieldsStorage',
        ),
        migrations.DeleteModel(
            name='Forms',
        ),
    ]
