# Generated by Django 3.1 on 2020-10-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200917_0044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
