# Generated by Django 3.1 on 2020-09-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Menu Name')),
                ('icon', models.CharField(max_length=50, verbose_name='İcon label')),
                ('url', models.URLField(verbose_name='Menu URL')),
                ('is_menu', models.BooleanField(default=False, verbose_name='is Menu')),
                ('is_menu_item', models.BooleanField(default=False, verbose_name='is Menu Item')),
                ('target', models.IntegerField(default=0, verbose_name='Target id')),
                ('is_dash', models.BooleanField(default=False, verbose_name='is Dash Menu')),
            ],
        ),
    ]
