# Generated by Django 3.1 on 2020-09-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_dash',
        ),
    ]
