# Generated by Django 3.1 on 2020-09-16 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Kategori İsmi')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Kategori Bağlantı')),
                ('description', models.CharField(max_length=100, verbose_name='Kategori Açıklaması')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Etiket İsmi')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Etiket Bağlantı')),
                ('description', models.CharField(max_length=100, verbose_name='Etiket Açıklaması')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Başlık')),
                ('content', models.CharField(max_length=150, verbose_name='İçerik')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Öne Çıkan Resim')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Kalıcı Bağlantı')),
                ('blocked', models.BooleanField(default=False, verbose_name='Block')),
                ('author', models.ForeignKey(on_delete=post.models.Post.donot, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PostLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.label', verbose_name='Label of Post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='post.post', verbose_name='Post of Label')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='Category of Post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='post.post', verbose_name='Post of Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150, verbose_name='Comment Of Post')),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='Username of Comment Writer')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email of Comment Writer')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post', verbose_name='Post Comment')),
                ('writer', models.ForeignKey(on_delete=post.models.Comment.donot, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
