# Generated by Django 3.1 on 2020-09-19 16:34

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Of Post Type')),
                ('description', models.CharField(max_length=150, verbose_name='Description Of Post Type')),
                ('singular_name', models.CharField(max_length=50, verbose_name='Singlar Name Of Post Type')),
                ('all_items', models.CharField(max_length=50, verbose_name='Label Of All Items Of Post Type')),
                ('view_item', models.CharField(max_length=50, verbose_name='Label Of View Item Of Post Type')),
                ('add_new_item', models.CharField(max_length=50, verbose_name='Label Of Adding New Item Of Post Type')),
                ('add_new', models.CharField(max_length=50, verbose_name='Label Of Adding New Of Post Type')),
                ('edit_item', models.CharField(max_length=50, verbose_name='Label Of Editing Item Of Post Type')),
                ('not_found', models.CharField(max_length=50, verbose_name='Label Of Not Found Of Post Type')),
                ('update_item', models.CharField(max_length=50, verbose_name='Label Of Updating Item Of Post Type')),
                ('search_items', models.CharField(max_length=50, verbose_name='Label Of Searching Items Of Post Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='blocked',
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default=0, max_length=150, verbose_name='Özet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='is Draft'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='is Publish'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ForeignKey(default=0, on_delete=post.models.Post.donot, related_name='postsoftype', to='post.posttype', verbose_name='Post Type'),
            preserve_default=False,
        ),
    ]
