# Generated by Django 3.1 on 2020-10-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200929_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttermstorage',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termposts', to='post.postterm', verbose_name='Term of Post'),
        ),
    ]
