# Generated by Django 3.1 on 2020-09-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Field Name')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Field Description')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required?')),
                ('field_type', models.CharField(max_length=50, verbose_name='Field Type')),
                ('placeholder', models.CharField(max_length=50, verbose_name='Field Placeholder')),
                ('custom_css', models.TextField(blank=True, null=True, verbose_name='Field Custom CSS')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Form Name')),
                ('slug', models.SlugField(default='', verbose_name='Form Slug')),
                ('description', models.CharField(blank=True, max_length=15, null=True, verbose_name='Form Name')),
                ('to_url', models.URLField(max_length=150, verbose_name='URL to ?')),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldsStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.formfields', verbose_name='Field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.forms', verbose_name='Form')),
            ],
        ),
    ]
